---
- name: My Test Playbook
  hosts: webservers
  become: yes
  tasks:
  - name: Install package
    yum:
      name: ['git', 'make', 'gcc', 'wget', 'telnet', 'tree', 'which', 'docker*' ]
      state: installed


